//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class BSO
    {
        public int id_BSO { get; set; }
        public string number_BSO { get; set; }
        public Nullable<System.DateTime> date_BSO { get; set; }
        public Nullable<int> id_request_reception { get; set; }
        public string ispolnitel { get; set; }
        public Nullable<System.DateTime> date_execution { get; set; }
        public Nullable<int> kol_ust_gor_schetch { get; set; }
        public Nullable<int> kol_ust_hol_schetch { get; set; }
        public Nullable<int> kol_zamena_hol_schetch { get; set; }
        public Nullable<int> kol_zamena_gor_schetch { get; set; }
        public Nullable<decimal> sum_nal_installation { get; set; }
        public Nullable<decimal> sum_nal_zamena { get; set; }
        public Nullable<decimal> sum_nal_TO { get; set; }
        public Nullable<decimal> sum_nal_shefmontazh { get; set; }
        public Nullable<decimal> sum_nal_dopolniteln_work { get; set; }
        public Nullable<decimal> sum_nal_dopolniteln_materialy { get; set; }
        public Nullable<decimal> avans { get; set; }
        public decimal sum_nal_po_BSO { get; set; }
        public Nullable<decimal> sum_beznal_installation { get; set; }
        public Nullable<decimal> sum_beznal_zamena { get; set; }
        public Nullable<decimal> sum_beznal_TO { get; set; }
        public decimal sum_beznal_po_BSO { get; set; }
        public string ispolnitel_proveden_TO { get; set; }
        public Nullable<System.DateTime> zaplanirovan_date_TO { get; set; }
    
        public virtual Request_reception Request_reception { get; set; }
    }
}
