//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public Client()
        {
            this.Adr_installation = new HashSet<Adr_installation>();
        }
    
        public int id_client { get; set; }
        public string famil { get; set; }
        public string f_name { get; set; }
        public string s_name { get; set; }
        public string tel { get; set; }
        public string number_pasp { get; set; }
    
        public virtual ICollection<Adr_installation> Adr_installation { get; set; }
    }
}
