//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class FullRequest
    {
        public string city_town { get; set; }
        public string raion { get; set; }
        public string street { get; set; }
        public Nullable<int> house { get; set; }
        public string korp { get; set; }
        public Nullable<int> flat { get; set; }
        public Nullable<int> id_metro { get; set; }
        public Nullable<int> podezd { get; set; }
        public Nullable<int> etag { get; set; }
        public string domofon { get; set; }
        public string famil { get; set; }
        public string f_name { get; set; }
        public string s_name { get; set; }
        public string tel { get; set; }
        public string number_pasp { get; set; }
        public string status { get; set; }
        public Nullable<int> time_of_work { get; set; }
        public string kind_of_work { get; set; }
        public Nullable<System.DateTime> date_zaplanirovan_vyezd { get; set; }
        public string vremya { get; set; }
        public string ispolnitel { get; set; }
        public string reason_perenosa { get; set; }
        public Nullable<bool> vyezd_or_perezvon { get; set; }
        public Nullable<System.DateTime> datetime_reception { get; set; }
        public Nullable<System.DateTime> date_request { get; set; }
        public Nullable<int> id_adr_installation { get; set; }
        public int id_request { get; set; }
        public Nullable<int> id_request_execution { get; set; }
        public Nullable<int> id_request_buhg { get; set; }
        public Nullable<int> id_request_snab { get; set; }
        public Nullable<bool> otkaz { get; set; }
        public Nullable<int> id_status { get; set; }
        public Nullable<int> id_kind_of_work { get; set; }
        public string dispetcher { get; set; }
        public Nullable<decimal> sum_contract { get; set; }
        public Nullable<bool> nal_money { get; set; }
        public Nullable<decimal> sum_contract_TO { get; set; }
        public Nullable<bool> nal_oplata_TO { get; set; }
        public string marka_teplo_schetch { get; set; }
        public string marka_gor_schetch { get; set; }
        public string marka_hol_schetch { get; set; }
        public Nullable<int> id_hol_schetch { get; set; }
        public Nullable<int> id_gor_schetch { get; set; }
        public Nullable<int> id_teplo_schetch { get; set; }
        public Nullable<int> kol_teplo { get; set; }
        public Nullable<int> kol_hol { get; set; }
        public Nullable<int> kol_gor { get; set; }
        public string full_name { get; set; }
        public string name_metro { get; set; }
        public Nullable<int> Expr1 { get; set; }
        public Nullable<System.DateTime> datetime_vyezda_montazhnika { get; set; }
    }
}
