//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class G_Schetchik
    {
        public G_Schetchik()
        {
            this.Request_snab = new HashSet<Request_snab>();
        }
    
        public int id_gor_schetch { get; set; }
        public string marka_gor_schetch { get; set; }
    
        public virtual ICollection<Request_snab> Request_snab { get; set; }
    }
}
