//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kind_of_work
    {
        public Kind_of_work()
        {
            this.Request_reception = new HashSet<Request_reception>();
        }
    
        public int id_kind_of_work { get; set; }
        public string kind_of_work1 { get; set; }
    
        public virtual ICollection<Request_reception> Request_reception { get; set; }
    }
}
