//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Params
    {
        public int id_param { get; set; }
        public Nullable<int> param_int { get; set; }
        public Nullable<System.DateTime> p_date_ost { get; set; }
        public Nullable<System.DateTime> p_date_from { get; set; }
        public Nullable<System.DateTime> p_date_to { get; set; }
        public string param_string { get; set; }
    }
}
