//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Perenos_request
    {
        public Perenos_request()
        {
            this.Request_reception = new HashSet<Request_reception>();
        }
    
        public int id_perenos_request { get; set; }
        public Nullable<System.DateTime> date_zaplanirovan_vyezd { get; set; }
        public string vremya { get; set; }
        public string ispolnitel { get; set; }
        public string reason_perenosa { get; set; }
        public Nullable<bool> vyezd_or_perezvon { get; set; }
        public string dispetcher { get; set; }
        public Nullable<System.DateTime> datetime_reception { get; set; }
    
        public virtual ICollection<Request_reception> Request_reception { get; set; }
    }
}
