//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Postavshiki
    {
        public Postavshiki()
        {
            this.Prihod1 = new HashSet<Prihod1>();
        }
    
        public int id_postavsh { get; set; }
        public string name_postavsh { get; set; }
        public string adres { get; set; }
        public string tel { get; set; }
        public string fax { get; set; }
        public string e_mail { get; set; }
        public string manager { get; set; }
        public string tel_manager { get; set; }
    
        public virtual ICollection<Prihod1> Prihod1 { get; set; }
    }
}
