//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prihod1
    {
        public Prihod1()
        {
            this.Prihod2 = new HashSet<Prihod2>();
        }
    
        public int id { get; set; }
        public System.DateTime data_prihod { get; set; }
        public int id_postavsh { get; set; }
    
        public virtual Postavshiki Postavshiki { get; set; }
        public virtual ICollection<Prihod2> Prihod2 { get; set; }
    }
}
