//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM
{
    using System;
    using System.Collections.Generic;
    
    //public partial class Rashod_2
    //{
    //    public int id_rashod_2 { get; set; }
    //    public int id { get; set; }
    //    public int id_material { get; set; }
    //    public int kod_ed_izm { get; set; }
    //    public decimal kol { get; set; }
    //    public decimal cena { get; set; }
    
    //    public virtual Materialy Materialy { get; set; }
    //    public virtual Rashod1 Rashod1 { get; set; }
    //}
}
