//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request_buhg
    {
        public Request_buhg()
        {
            this.Request_reception = new HashSet<Request_reception>();
        }
    
        public int id_request_buhg { get; set; }
        public Nullable<decimal> sum_contract { get; set; }
        public Nullable<bool> nal_money { get; set; }
        public Nullable<decimal> sum_contract_TO { get; set; }
        public Nullable<bool> nal_oplata_TO { get; set; }
    
        public virtual ICollection<Request_reception> Request_reception { get; set; }
    }
}
