//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request_reception
    {
        public Request_reception()
        {
            this.BSO = new HashSet<BSO>();
        }
    
        public int id_request { get; set; }
        public Nullable<System.DateTime> date_request { get; set; }
        public Nullable<int> id_adr_installation { get; set; }
        public Nullable<int> id_request_execution { get; set; }
        public Nullable<int> id_request_buhg { get; set; }
        public Nullable<int> id_request_snab { get; set; }
        public Nullable<bool> otkaz { get; set; }
        public string dispetcher { get; set; }
        public Nullable<int> id_status { get; set; }
        public Nullable<int> id_kind_of_work { get; set; }
        public Nullable<int> id_perenos_request { get; set; }
        public Nullable<System.DateTime> date_otkaza { get; set; }
        public string reason_otkaza { get; set; }
    
        public virtual Adr_installation Adr_installation { get; set; }
        public virtual ICollection<BSO> BSO { get; set; }
        public virtual Kind_of_work Kind_of_work { get; set; }
        public virtual Perenos_request Perenos_request { get; set; }
        public virtual Request_buhg Request_buhg { get; set; }
        public virtual Request_snab Request_snab { get; set; }
        public virtual Status Status { get; set; }
        public virtual Request_attachment Request_attachment { get; set; }
    }
}
