//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request_attachment
    {
        public Request_attachment()
        {
            this.Request_reception = new HashSet<Request_reception>();
        }
    
        public int id_request_execution { get; set; }
        public Nullable<System.DateTime> datetime_vyezda_montazhnika { get; set; }
        public Nullable<int> time_of_work { get; set; }
        public Nullable<int> id_mont { get; set; }
        public Nullable<System.DateTime> date_execution { get; set; }
    
        public virtual Montazhniki Montazhniki { get; set; }
        public virtual ICollection<Request_reception> Request_reception { get; set; }
    }
}
