//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestList
    {
        public int id_client { get; set; }
        public string famil { get; set; }
        public string f_name { get; set; }
        public string s_name { get; set; }
        public int id_request { get; set; }
    }
}
