//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sotrudniki
    {
        public int id_sotrudnik { get; set; }
        public string full_name { get; set; }
        public string parol { get; set; }
        public string rol { get; set; }
    }
}
