//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Status
    {
        public Status()
        {
            this.Request_reception = new HashSet<Request_reception>();
        }
    
        public int id_status { get; set; }
        public string status1 { get; set; }
    
        public virtual ICollection<Request_reception> Request_reception { get; set; }
    }
}
