//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmp_OborotkaSklad
    {
        public string Номенклатура { get; set; }
        public string ЕдИзм { get; set; }
        public Nullable<decimal> MaxZenasNDS { get; set; }
        public Nullable<decimal> ОстатокВх { get; set; }
        public Nullable<decimal> Приход { get; set; }
        public Nullable<decimal> Выдача { get; set; }
        public Nullable<decimal> ОстатокИсх { get; set; }
        public Nullable<decimal> ОстатокИсхРубсНДС { get; set; }
        public string Artikul { get; set; }
    }
}
