//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class vMaterialy
    {
        public int id_material { get; set; }
        public string NameMaterial { get; set; }
        public Nullable<int> ves1shtuki { get; set; }
        public Nullable<int> kol_v_upak { get; set; }
        public Nullable<int> kol_v_tare { get; set; }
        public string mesto_hraneniya { get; set; }
        public Nullable<int> norma_rashoda_na1schetchik { get; set; }
        public string nameEI { get; set; }
        public string artikul { get; set; }
    }
}
