//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vydacha_mater1
    {
        public Vydacha_mater1()
        {
            this.Vydacha_mater2 = new HashSet<Vydacha_mater2>();
        }
    
        public int id_vydacha_m1 { get; set; }
        public Nullable<System.DateTime> data_vydacha { get; set; }
        public Nullable<int> id_mont { get; set; }
        public Nullable<int> id_request_snab { get; set; }
        public Nullable<bool> vydano { get; set; }
    
        public virtual ICollection<Vydacha_mater2> Vydacha_mater2 { get; set; }
        public virtual Request_snab Request_snab { get; set; }
        public virtual Montazhniki Montazhniki { get; set; }
    }
}
