//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vydacha_mater2
    {
        public int id_vydacha_m2 { get; set; }
        public Nullable<int> id_vydacha_m1 { get; set; }
        public Nullable<int> id_mater { get; set; }
        public Nullable<int> kol { get; set; }
    
        public virtual Vydacha_mater1 Vydacha_mater1 { get; set; }
        public virtual Materialy Materialy { get; set; }
    }
}
